apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: second-brain
resources:
  - namespace.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - second-brain-configmap.yaml
  - second-brain-secret.yaml
  - second-brain-deployment.yaml
  - second-brain-service.yaml
  - collector-deployment.yaml
