apiVersion: v1
kind: Service
metadata:
  name: second-brain
  namespace: second-brain
  labels:
    app: second-brain
spec:
  type: NodePort
  selector:
    app: second-brain
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30920
      protocol: TCP
