package tune

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/baekenough/second-brain/internal/dataset"
	"github.com/baekenough/second-brain/internal/model"
)

// Search termination constants. Neither is exported and neither is
// configurable: the urge to raise them is the urge to overfit. Three sweeps
// over six axes is roughly 135 evaluations, which is a bounded amount of work
// against a database that is also serving.
const (
	maxSweeps = 3
	// minSweepGain is the total objective improvement a whole sweep must produce
	// to justify another one.
	minSweepGain = 1e-4
)

// SearchSpace is the grid the optimiser is allowed to move on.
//
// The grid is explicit rather than generated by a loop over a range and a step
// because 0.05 + 0.25 is not 0.30 in float64, and a candidate weight that
// differs from the recorded one in the sixteenth decimal is a reproducibility
// problem waiting to be debugged at the worst possible time.
type SearchSpace struct {
	FTS        []float64
	Vec        []float64
	Bigm       []float64
	SummaryVec []float64
	Entity     []float64
	RRFK       []float64
}

// DefaultSpace is the grid from plan §2.4.
//
// The lower bounds of SummaryVec and Entity are positive, not zero, and that is
// the load-bearing detail of this whole file. In model.SearchWeights, a zero
// SummaryVec means "unset — let the coverage gate decide" and a non-positive
// EntityWeight means "explicitly disabled". Either value would make the search
// report a configuration whose behaviour it never actually measured. Turning
// the summary lane off is a separate, explicitly evaluated candidate
// (DisableSummaryVec), not a point on this grid.
func DefaultSpace() SearchSpace {
	return SearchSpace{
		FTS:        []float64{0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0},
		Vec:        []float64{0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0},
		Bigm:       []float64{0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0},
		SummaryVec: []float64{0.05, 0.3, 0.55, 0.8, 1.05, 1.3},
		Entity:     []float64{0.05, 0.3, 0.55, 0.8, 1.05, 1.3},
		RRFK:       []float64{20, 40, 60, 80, 120},
	}
}

// Validate rejects a grid the optimiser cannot honestly search.
func (s SearchSpace) Validate() error {
	for _, ax := range s.axes() {
		if len(ax.values) == 0 {
			return fmt.Errorf("tune: search space axis %q is empty", ax.name)
		}
		for _, v := range ax.values {
			if math.IsNaN(v) || math.IsInf(v, 0) {
				return fmt.Errorf("tune: search space axis %q contains a non-finite value", ax.name)
			}
			if v <= 0 {
				// Applies to every axis: model.SearchWeights.Defaults()
				// replaces zero and negative fields, so a candidate at or below
				// zero would be silently rewritten before it reached search.
				return fmt.Errorf("tune: search space axis %q contains %v; weights must be positive "+
					"(zero and negative carry separate meanings in model.SearchWeights)", ax.name, v)
			}
		}
	}
	return nil
}

// axis is one searchable coordinate. The getter/setter pair keeps the sweep
// loop free of a switch over field names.
type axis struct {
	name   string
	values []float64
	get    func(model.SearchWeights) float64
	set    func(*model.SearchWeights, float64)
}

// axes returns the coordinates in a FIXED order. The order is part of the
// algorithm's output — coordinate search is path dependent — so it must never
// come from a map.
func (s SearchSpace) axes() []axis {
	return []axis{
		{"fts", s.FTS,
			func(w model.SearchWeights) float64 { return w.FTSWeight },
			func(w *model.SearchWeights, v float64) { w.FTSWeight = v }},
		{"vec", s.Vec,
			func(w model.SearchWeights) float64 { return w.VecWeight },
			func(w *model.SearchWeights, v float64) { w.VecWeight = v }},
		{"bigm", s.Bigm,
			func(w model.SearchWeights) float64 { return w.BigmWeight },
			func(w *model.SearchWeights, v float64) { w.BigmWeight = v }},
		{"summary_vec", s.SummaryVec,
			func(w model.SearchWeights) float64 { return w.SummaryVec },
			func(w *model.SearchWeights, v float64) { w.SummaryVec = v }},
		{"entity", s.Entity,
			func(w model.SearchWeights) float64 { return w.EntityWeight },
			func(w *model.SearchWeights, v float64) { w.EntityWeight = v }},
		{"rrf_k", s.RRFK,
			func(w model.SearchWeights) float64 { return w.RRFK },
			func(w *model.SearchWeights, v float64) { w.RRFK = v }},
	}
}

// Result is what a search run produces.
type Result struct {
	// Best is the winning configuration, always a point on the grid.
	Best model.SearchWeights
	// BestObjective is its objective on the TRAINING set. It is not a holdout
	// number and must never be presented as one.
	BestObjective float64
	// StartObjective is the objective of the grid-snapped starting point, so
	// that "how much did searching actually buy" is answerable from the record.
	StartObjective float64
	Sweeps         int
	Evals          int
	// Trace is a human-readable log of accepted moves. It contains weights and
	// objective values only — no query text, no document IDs.
	Trace []string
}

// Coordinate runs coordinate search over the training set.
//
// The signature has no *dataset.HoldoutSet parameter, and that absence is the
// design: there is no argument position into which a holdout set could be
// passed by mistake, so no reviewer has to check that this function does not
// peek. The caller measures the holdout set separately, twice, through Judge.
//
// eval is supplied by the caller rather than built here so that this function
// stays a pure optimiser over a scored space — it is tested against synthetic
// objectives with no database in sight.
func Coordinate(
	ctx context.Context,
	train *dataset.TrainSet,
	base model.SearchWeights,
	space SearchSpace,
	eval func(context.Context, model.SearchWeights) (dataset.Metrics, error),
) (Result, error) {
	if train == nil || train.Queries() == 0 {
		return Result{}, errors.New("tune: coordinate search needs a non-empty training set")
	}
	if eval == nil {
		return Result{}, errors.New("tune: coordinate search needs an evaluation function")
	}
	if err := space.Validate(); err != nil {
		return Result{}, err
	}

	axes := space.axes()
	res := Result{}

	// The starting point is snapped onto the grid before the first measurement.
	// Starting from an off-grid point would mean the reported "start objective"
	// belongs to a configuration that no later candidate can return to, and
	// (for a default SearchWeights) it would begin the run at SummaryVec == 0 —
	// the value this optimiser must never report.
	best := snap(base.Defaults(), axes)
	best.DisableSummaryVec = false

	metrics, err := eval(ctx, best)
	if err != nil {
		return Result{}, fmt.Errorf("tune: evaluate starting point: %w", err)
	}
	res.Evals++
	bestObj := Objective(metrics)
	res.StartObjective = bestObj
	res.Trace = append(res.Trace, fmt.Sprintf("start objective=%.6f %s", bestObj, describeWeights(best)))

	for sweep := 1; sweep <= maxSweeps; sweep++ {
		res.Sweeps = sweep
		sweepStart := bestObj

		for _, ax := range axes {
			current := ax.get(best)
			for _, v := range ax.values {
				// The incumbent value on this axis has already been measured as
				// part of `best`; re-measuring it would spend a database round
				// trip to learn a number we are holding.
				if v == current {
					continue
				}
				cand := best
				ax.set(&cand, v)

				m, err := eval(ctx, cand)
				if err != nil {
					return Result{}, fmt.Errorf("tune: evaluate candidate (%s=%v): %w", ax.name, v, err)
				}
				res.Evals++

				// Strictly greater: on a tie the incumbent stays. Combined with
				// the fixed axis and value order this makes the whole run
				// reproducible, which matters because a promotion has to be
				// explainable from the recorded weights alone.
				if obj := Objective(m); obj > bestObj {
					bestObj = obj
					best = cand
					current = v
					res.Trace = append(res.Trace,
						fmt.Sprintf("sweep=%d axis=%s value=%v objective=%.6f accepted", sweep, ax.name, v, obj))
				}
			}
		}

		if bestObj-sweepStart < minSweepGain {
			break
		}
	}

	// The summary-embedding lane cannot be switched off from inside the grid
	// (§DefaultSpace), so it is offered once as an explicit alternative. It has
	// to beat the grid winner by the same margin a sweep must produce, not
	// merely tie it, because turning a retrieval lane off is a larger change
	// than nudging a weight.
	off := best
	off.DisableSummaryVec = true
	m, err := eval(ctx, off)
	if err != nil {
		return Result{}, fmt.Errorf("tune: evaluate summary-lane-disabled candidate: %w", err)
	}
	res.Evals++
	if obj := Objective(m); obj > bestObj+minSweepGain {
		bestObj = obj
		best = off
		res.Trace = append(res.Trace,
			fmt.Sprintf("disable_summary_vec=true objective=%.6f accepted", obj))
	}

	res.Best = best
	res.BestObjective = bestObj
	return res, nil
}

// snap moves a configuration onto the grid, choosing the nearest value on each
// axis and, on a tie, the one that appears first.
func snap(w model.SearchWeights, axes []axis) model.SearchWeights {
	out := w
	for _, ax := range axes {
		cur := ax.get(w)
		bestV := ax.values[0]
		bestD := math.Abs(cur - bestV)
		for _, v := range ax.values[1:] {
			if d := math.Abs(cur - v); d < bestD {
				bestV, bestD = v, d
			}
		}
		ax.set(&out, bestV)
	}
	return out
}

// describeWeights renders a configuration for the trace. Weights only — this
// string ends up in logs and in the history row's metadata.
func describeWeights(w model.SearchWeights) string {
	return fmt.Sprintf("fts=%v vec=%v bigm=%v summary_vec=%v entity=%v rrf_k=%v disable_summary_vec=%v",
		w.FTSWeight, w.VecWeight, w.BigmWeight, w.SummaryVec, w.EntityWeight, w.RRFK, w.DisableSummaryVec)
}
