package setup_test

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/baekenough/second-brain/internal/setup"
)

func TestWriteEnv_CreatesFileWithCorrectMode(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	dest := filepath.Join(dir, ".env")

	pairs := map[string]string{
		"SLACK_BOT_TOKEN": "xoxb-secret",
		"SLACK_TEAM_ID":   "T12345678",
	}
	order := []string{"SLACK_BOT_TOKEN", "SLACK_TEAM_ID"}

	if err := setup.WriteEnv(dest, pairs, order); err != nil {
		t.Fatalf("WriteEnv: %v", err)
	}

	info, err := os.Stat(dest)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	if got := info.Mode().Perm(); got != 0o600 {
		t.Errorf("file mode = %04o, want 0600", got)
	}
}

func TestWriteEnv_ContentOrder(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	dest := filepath.Join(dir, ".env")

	pairs := map[string]string{
		"B_KEY": "bval",
		"A_KEY": "aval",
	}
	order := []string{"A_KEY", "B_KEY"}

	if err := setup.WriteEnv(dest, pairs, order); err != nil {
		t.Fatalf("WriteEnv: %v", err)
	}

	data, err := os.ReadFile(dest)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}

	content := string(data)
	aIdx := strings.Index(content, "A_KEY=")
	bIdx := strings.Index(content, "B_KEY=")
	if aIdx < 0 || bIdx < 0 {
		t.Fatalf("keys missing in output:\n%s", content)
	}
	if aIdx > bIdx {
		t.Errorf("A_KEY should appear before B_KEY; got:\n%s", content)
	}
}

func TestWriteEnv_BacksUpExistingFile(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	dest := filepath.Join(dir, ".env")

	// Write an initial .env.
	if err := os.WriteFile(dest, []byte("EXISTING=1\n"), 0o600); err != nil {
		t.Fatalf("setup: %v", err)
	}

	pairs := map[string]string{"NEW_KEY": "newval"}
	order := []string{"NEW_KEY"}

	if err := setup.WriteEnv(dest, pairs, order); err != nil {
		t.Fatalf("WriteEnv: %v", err)
	}

	// Check a backup file was created.
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("ReadDir: %v", err)
	}

	var bakFound bool
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), ".env.bak.") {
			bakFound = true
			// Verify the backup contains the original content.
			bak, err := os.ReadFile(filepath.Join(dir, e.Name()))
			if err != nil {
				t.Fatalf("read backup: %v", err)
			}
			if !strings.Contains(string(bak), "EXISTING=1") {
				t.Errorf("backup does not contain original content: %s", bak)
			}
		}
	}
	if !bakFound {
		t.Error("no .env.bak.* file created")
	}
}

func TestWriteEnv_MultilineEscaped(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	dest := filepath.Join(dir, ".env")

	json := `{"type":"service_account",` + "\n" + `"project_id":"my-project"}`
	pairs := map[string]string{"GDRIVE_CREDENTIALS_JSON": json}
	order := []string{"GDRIVE_CREDENTIALS_JSON"}

	if err := setup.WriteEnv(dest, pairs, order); err != nil {
		t.Fatalf("WriteEnv: %v", err)
	}

	data, err := os.ReadFile(dest)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}

	content := string(data)
	// The value must not contain a literal newline (only \n escape).
	for i, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, "GDRIVE_CREDENTIALS_JSON=") {
			val := strings.TrimPrefix(line, "GDRIVE_CREDENTIALS_JSON=")
			if strings.Contains(val, "\n") {
				t.Errorf("line %d: value contains literal newline", i)
			}
			if !strings.Contains(val, `\n`) {
				t.Errorf("line %d: escaped \\n not found in value: %s", i, val)
			}
			return
		}
	}
	t.Errorf("GDRIVE_CREDENTIALS_JSON key not found in output:\n%s", content)
}

func TestWriteEnv_AtomicOnPermissionError(t *testing.T) {
	t.Parallel()

	if os.Getuid() == 0 {
		t.Skip("running as root — permission checks are skipped")
	}

	dir := t.TempDir()
	// Make dir read-only so CreateTemp fails.
	if err := os.Chmod(dir, 0o555); err != nil {
		t.Fatalf("chmod dir: %v", err)
	}
	t.Cleanup(func() { _ = os.Chmod(dir, 0o755) })

	dest := filepath.Join(dir, ".env")
	err := setup.WriteEnv(dest, map[string]string{"K": "v"}, []string{"K"})
	if err == nil {
		t.Fatal("expected error writing to read-only directory, got nil")
	}
}

func TestWriteEnv_EmptyPairsWritesHeader(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	dest := filepath.Join(dir, ".env")

	if err := setup.WriteEnv(dest, map[string]string{}, []string{}); err != nil {
		t.Fatalf("WriteEnv: %v", err)
	}

	data, err := os.ReadFile(dest)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}

	if !strings.Contains(string(data), "Generated by second-brain setup wizard") {
		t.Errorf("header missing from empty .env:\n%s", data)
	}
}

// BenchmarkWriteEnv measures the cost of writing 10 keys atomically.
func BenchmarkWriteEnv(b *testing.B) {
	dir := b.TempDir()
	pairs := make(map[string]string, 10)
	order := make([]string, 10)
	for i := range 10 {
		k := fmt.Sprintf("KEY_%02d", i)
		pairs[k] = "value"
		order[i] = k
	}

	b.ResetTimer()
	for range b.N {
		dest := filepath.Join(dir, fmt.Sprintf(".env.%d", b.N))
		if err := setup.WriteEnv(dest, pairs, order); err != nil {
			b.Fatal(err)
		}
	}
}
