package setup

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const (
	envFilename = ".env"
	fileMode    = 0o600
)

// WriteEnv atomically writes key=value pairs to dest (typically ".env").
//
// Algorithm:
//  1. If dest already exists, back it up to <dir>/.env.bak.<unix-ts>.
//  2. Write a temp file in the same directory with mode 0600.
//  3. os.Rename to atomically replace the destination.
//
// The caller provides the full destination path.
func WriteEnv(dest string, pairs map[string]string, order []string) error {
	dir := filepath.Dir(dest)
	if dir == "" {
		dir = "."
	}

	// Step 1: backup if exists.
	if _, err := os.Stat(dest); err == nil {
		bak := fmt.Sprintf("%s.bak.%d", dest, time.Now().Unix())
		if err := copyFile(dest, bak); err != nil {
			return fmt.Errorf("backup existing .env: %w", err)
		}
	}

	// Step 2: build content.
	var sb strings.Builder
	sb.WriteString("# Generated by second-brain setup wizard\n")
	sb.WriteString("# Edit manually or re-run: go run ./cmd/collector/ setup\n\n")

	for _, key := range order {
		val, ok := pairs[key]
		if !ok {
			continue
		}
		// Escape newlines in values (e.g. multiline JSON credentials).
		escaped := strings.ReplaceAll(val, "\n", "\\n")
		sb.WriteString(key)
		sb.WriteByte('=')
		sb.WriteString(escaped)
		sb.WriteByte('\n')
	}

	content := sb.String()

	// Step 3: write to temp file in same directory, then rename.
	tmp, err := os.CreateTemp(dir, ".env.tmp.*")
	if err != nil {
		return fmt.Errorf("create temp file: %w", err)
	}
	tmpName := tmp.Name()

	// Ensure cleanup on failure path.
	success := false
	defer func() {
		if !success {
			_ = os.Remove(tmpName)
		}
	}()

	if err := tmp.Chmod(fileMode); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("chmod temp file: %w", err)
	}

	if _, err := tmp.WriteString(content); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("write temp file: %w", err)
	}

	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("sync temp file: %w", err)
	}

	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temp file: %w", err)
	}

	if err := os.Rename(tmpName, dest); err != nil {
		return fmt.Errorf("rename temp file to %s: %w", dest, err)
	}

	success = true
	return nil
}

// copyFile copies src to dst with mode 0600.
func copyFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return os.WriteFile(dst, data, fileMode)
}

// EnvFilePath returns the path to .env relative to the process working
// directory. Exported for use in tests.
func EnvFilePath() string {
	return envFilename
}
